const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: '7,500',
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: '48,500',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: '78,500',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: '33,000',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: '4,100',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: '2,500',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Apple iPhone 13',
    image: '/images/ip13.jpg',
    description:
      '15 cm (6.1-inch) Super Retina XDR display  Cinematic mode adds shallow depth of field and shifts focus automatically in your videosAdvanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording 12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording A15 Bionic chip for lightning-fast performance',
    brand: 'Apple',
    category: 'Electronics',
    price: '56,999',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Zebronics Jet PRO Premium Wired Gaming Headphone',
    image: '/images/h1.webp',
    description:
      'Get immersed into your gaming world with the 40mm Neodymium drivers which produce the best sound signature for a Gaming headphone! Powerful Bass, minor details like footsteps and gunshots, Clear vocals are easily audible with ZEB-JET PRO!',
    brand: 'ZEBRONICS',
    category: 'Electronics',
    price: '1,899',
    countInStock: 0,
    rating: 3.9,
    numReviews: 8,
  },
  {
    _id: '9',
    name: 'Apple 2023 MacBook Air',
    image: '/images/macbook.jpg',
    description:
      'IMPRESSIVELY BIG, IMPOSSIBLY THIN — The 15-inch MacBook Air makes room for more of what you love with a spacious Liquid Retina display. The durable 100% recycled aluminium enclosure is strikingly thin and light. SUPERCHARGED BY M2 — Get more done faster with a powerful 8-core CPU, 10-core GPU and up to 24GB of unified memory.  UP TO 18 HOURS OF BATTERY LIFE — Go all day with the power-efficient performance of the Apple M2 chip. (Battery life varies by use and configuration. See our website for more information.) SPACIOUS, BEAUTIFUL DISPLAY — The high-resolution, 38.91-centimetre (15.3-inch) Liquid Retina display features 500 nits of brightness, P3 wide colour and support for one billion colours for vibrant images and incredible detail. (The display on the 15-inch MacBook Air has rounded corners at the top. When measured as a standard rectangular shape, the screen is 38.91 centimetres (15.3 inches) diagonally (actual viewable area is less.) SILENT DESIGN — MacBook Air features a fanless design that runs completely silent, no matter the task.',
    brand: 'Apple',
    category: 'Electronics',
    price: '1,34,190',
    countInStock: 0,
    rating: 4.0,
    numReviews: 25,
  },
  {
    _id: '10',
    name: 'Logitech G213 Prodigy USB Gaming Keyboard',
    image: '/images/logitechkeyboard.webp',
    description:
      'Brilliant Color Spectrum Illumination Personalize five individual lighting zones from a spectrum of over 16.8 million colors. Change colors to match your setup, specific games, or to showcase your favorite colors. Synchronize lighting effects with other Logitech G devices using Logitech Gaming Software. Low light leak around each keycap means less more light comes through the lettering – and less leaks around the keycaps. This helps make the illumination of each key more brilliant, making it easier to find your keys in the dark',
    brand: 'Logitech G',
    category: 'Electronics',
    price: '4,495',
    countInStock: 10,
    rating: 4.5,
    numReviews: 50,
  },
  {
    _id: '11',
    name: 'Samsung 27-inches 68.4cm 2560 X 1440 (QHD) Pixels Odyssey G7 Gaming, 240 Hz, 1ms, 2K, Curved Monitor',
    image: '/images/samsungmonitor.jpg',
    description:
      '1000R 27-inch gaming monitor – Industry-leading monitor screen for maximum eye comfort and immersive viewing Blazing fast 1ms (GTG) response time and 240Hz refresh rate for smooth gameplay Extra detail and clarity with 2560×1440p QHD resolution and true-to-life colors with Samsung’ s QLED technology Freesync Premium Pro and Gsync compatible technology - No image tearing or stuttering HDR 600 standard provides high luminance 600 nit shows small hidden details in the lightest and darkest scenes Windows 10 certified Connect easily - HDMI and DP for PS4, Xbox, PC, laptop, Macbook, dual monitor',
    brand: 'Samsung',
    category: 'Electronics',
    price: '37,699',
    countInStock: 9,
    rating: 4.1,
    numReviews: 100,
  },
  {
    _id: '12',
    name: 'Apple Watch SE (GPS + Cellular, 44mm)',
    image: '/images/appleWatch.jpg',
    description:
      'Stay connected to family and friends with calls, texts and email, even when you don’t have your phone;Stream music and podcasts on the go, and leave your phone at home Take calls and reply to texts, right from your wrist;Track your daily activity on Apple Watch and see your trends in the Fitness app on iPhone Track new tai chi and pilates workouts, in addition to favourites like running, yoga, swimming and dance;Hike smarter with built-in compass and real-time elevation readings Stay on top of your health with high and low heart rate, and irregular heart rhythm notifications;Apple Watch can detect if you’ve taken a hard fall, then automatically call emergency services for you; Emergency SOS lets you call for help when you need it;Sync your favourite music and podcasts Included Components: Apple Watch, Band, 1m Magnetic Charging Cable; Compatible Devices: Smartphone',
    brand: 'Apple',
    category: 'Electronics',
    price: '36,900',
    countInStock: 16,
    rating: 4.6,
    numReviews: 86,
  },
];

export default products;
